blocks:
  citation:
      displayName: "Citation Metadata"
      fields:
        - titleValue:
            source: ["name"]
            type: "single"
        - datasetDescription:
            source: ["description"]
            type: "list"
            item_key: "descriptionValue"
        - author:
            source: ["creator", "author"]
            type: "complex_list"
            mapping:
              authorName: ["name", "givenName"] # Some contexts use givenName
              authorAffiliation: ["affiliation.name"]
        - keyword:
            source: ["keywords"]
            type: "list"
            item_key: "keywordValue"
        - subject:
            default: "Agricultural Sciences"
            type: "list"
        - publicationDate:
            source: ["datePublished"]
            type: "single"
        - license:
            source: ["license"]
            type: "single"

  geospatial:
    displayName: "Geospatial Metadata"
    fields:
      - westLongitude:
            source: ["spatialCoverage.geo.box"]
            type: "single"
