[project]
name = "to-dataverse-json"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyld>=2.0.4",
    "pyyaml>=6.0.3",
]
